version: '3'
services:
  web:
    image: node:14
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && node server.js"
    environment:
      - PORT=8080
    expose:
      - 8080

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"